api:
  dashboard: true

entryPoints:
  postgres:
    address: :5432

  web:
    address: :80
    http:
      redirections:
        entryPoint:
          to: websecure

  websecure:
    address: :443
    http:
      middlewares:
        - secureHeaders@file
      tls:
        certResolver: letsencrypt

providers:
  docker:
    endpoint: 'unix:///var/run/docker.sock'
    exposedByDefault: false
  file:
    filename: /configurations/dynamic.yml

certificatesResolvers:
  letsencrypt:
    acme:
      email: mertalp.ulus@gmail.com # TODO change to admin email
      storage: acme.json
      keyType: EC384
      httpChallenge:
        entryPoint: web
