export enum EmailType {
  VERIFICATION_EMAIL = '  VERIFICATION_EMAIL',
  RESET_PASSWORD = 'RESET_PASSWORD',
  PASSWORD_CHANGED = 'PASSWORD_CHANGED',
  USER_REGISTERED_EMAIL_TO_SUPERUSER = 'USER_REGISTERED_EMAIL_TO_SUPERUSER',
  REGISTRATION_APPROVAL_EMAIL_TO_USER = 'REGISTRATION_APPROVAL_EMAIL_TO_USER',
  REGISTRATION_DECLINATION_EMAIL_TO_USER = 'REGISTRATION_DECLINATION_EMAIL_TO_USER',
  REGISTRATION_REQUEST_RECEIVED_EMAIL_TO_USER = 'REGISTRATION_REQUEST_RECEIVED_EMAIL_TO_USER',
  ACCOUNT_DELETED = 'ACCOUNT_DELETED',
}
