name: Run AMD64 build

on:
  push:
    branches:
      - deployment

jobs:
  docker:
    name: Build and push docker image
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v2

      - name: Set Docker Image Tag
        id: image_tag
        run: |
          if [[ "${{github.base_ref}}" == "deployment" || "${{github.ref}}" == "refs/heads/deployment" ]]; then
            echo "::set-output name=IMAGE_TAG::amd64"
          fi

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/echtzeitsysteme/echtzeitkiosk-backend:${{ steps.image_tag.outputs.IMAGE_TAG }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64
